### ISSUE TITLE
Link to presentation is missing

### ISSUE THREAD

**Issue by lubusax** [tivisse/odoodays-2019#1]
Thank you for your presentation  during Odoo Experience 2019, which was very useful and easy to follow. I am not able to find a link to your presentation. You said you would like to share it with us.

**Comment by tate11** [comment]
https://github.com/tivisse/odoodays-2019/blob/1cdc27dd1fbed0f1e2f623ef01b62942b6633b78/plant_nursery/static/pdf/Mixins%202019%20-%20WIP.pdf

**Comment by lubusax** [comment]
Are you sure this is the link to the presentation?

**Comment by tivisse** [comment]
Hi @lubusax 

Thanks for the feedback.

The slides have been added at : https://github.com/tivisse/odooplants/blob/13.0/plant_nursery/static/pdf/OXP%202019%20-%20Develop%20an%20App%20with%20the%20Odoo%20Framework.pdf

Have a nice day,

Yannick.
